
/**
 * This file is auto-generated by scripts/fetch-okta-filter-options.js
 * Do not edit directly - regenerate if API data changes
 */

export interface FilterOption {
  value: string;
  label: string;
}

export const filterOptions = {
  "departments": [
    {
      "value": "",
      "label": "All Departments"
    },
    {
      "value": "2D",
      "label": "2D"
    },
    {
      "value": "2D Animation",
      "label": "2D Animation"
    },
    {
      "value": "3D",
      "label": "3D"
    },
    {
      "value": "Communications",
      "label": "Communications"
    },
    {
      "value": "Content Development",
      "label": "Content Development"
    },
    {
      "value": "Copy",
      "label": "Copy"
    },
    {
      "value": "Creative",
      "label": "Creative"
    },
    {
      "value": "Creative Direction",
      "label": "Creative Direction"
    },
    {
      "value": "Creative Technology",
      "label": "Creative Technology"
    },
    {
      "value": "Design",
      "label": "Design"
    },
    {
      "value": "development",
      "label": "Development"
    },
    {
      "value": "Executive",
      "label": "Executive"
    },
    {
      "value": "Finance",
      "label": "Finance"
    },
    {
      "value": "Freelance",
      "label": "Freelance"
    },
    {
      "value": "IT",
      "label": "IT"
    },
    {
      "value": "Live Action",
      "label": "Live Action"
    },
    {
      "value": "New Biz & Marketing",
      "label": "New Biz & Marketing"
    },
    {
      "value": "Operations",
      "label": "Operations"
    },
    {
      "value": "Post",
      "label": "Post"
    },
    {
      "value": "Post Production",
      "label": "Post Production"
    },
    {
      "value": "Production",
      "label": "Production"
    },
    {
      "value": "Project Management",
      "label": "Project Management"
    },
    {
      "value": "Strategy",
      "label": "Strategy"
    },
    {
      "value": "Strategy + Copywriting",
      "label": "Strategy + Copywriting"
    },
    {
      "value": "Talent",
      "label": "Talent"
    },
    {
      "value": "VTProDesign",
      "label": "Vtprodesign"
    },
    {
      "value": "Wild - Design",
      "label": "Wild - Design"
    },
    {
      "value": "Wild - Development",
      "label": "Wild - Development"
    },
    {
      "value": "Wild - Management",
      "label": "Wild - Management"
    },
    {
      "value": "Wild - Project Management",
      "label": "Wild - Project Management"
    },
    {
      "value": "Wild - UX",
      "label": "Wild - UX"
    }
  ],
  "locations": [
    {
      "value": "",
      "label": "All Locations"
    },
    {
      "value": "AMS",
      "label": "Amsterdam"
    },
    {
      "value": "ANY",
      "label": "Any"
    },
    {
      "value": "BGA",
      "label": "Giant Ant"
    },
    {
      "value": "CA",
      "label": "Ca"
    },
    {
      "value": "Founders",
      "label": "Founders"
    },
    {
      "value": "Giant Ant (Vancouver)",
      "label": "Giant Ant (Vancouver)"
    },
    {
      "value": "LON",
      "label": "London"
    },
    {
      "value": "LA",
      "label": "Los Angeles"
    },
    {
      "value": "NY",
      "label": "New York"
    },
    {
      "value": "Part and Sum",
      "label": "Part And Sum"
    },
    {
      "value": "Residence",
      "label": "Residence"
    },
    {
      "value": "SYD",
      "label": "Sydney"
    },
    {
      "value": "YVR",
      "label": "Vancouver"
    },
    {
      "value": "Wild",
      "label": "Wild"
    }
  ],
  "roles": [
    {
      "value": "",
      "label": "All Roles"
    },
    {
      "value": "2D Animation Director",
      "label": "2D Animation Director"
    },
    {
      "value": "2D Animator",
      "label": "2D Animator"
    },
    {
      "value": "2D Animator (AE)",
      "label": "2D Animator (ae)"
    },
    {
      "value": "2D Animator (Cel)",
      "label": "2D Animator (cel)"
    },
    {
      "value": "2D Animator/Creative Editor",
      "label": "2D Animator/creative Editor"
    },
    {
      "value": "2D Apprentice",
      "label": "2D Apprentice"
    },
    {
      "value": "3D Animation Lead",
      "label": "3D Animation Lead"
    },
    {
      "value": "3D Animation Supervisor",
      "label": "3D Animation Supervisor"
    },
    {
      "value": "3D Animator",
      "label": "3D Animator"
    },
    {
      "value": "3D Apprentice",
      "label": "3D Apprentice"
    },
    {
      "value": "3D Artist",
      "label": "3D Artist"
    },
    {
      "value": "3D Artist/Compositor",
      "label": "3D Artist/compositor"
    },
    {
      "value": "3D Design/Animation Supervisor",
      "label": "3D Design/animation Supervisor"
    },
    {
      "value": "3D Designer/Animator",
      "label": "3D Designer/animator"
    },
    {
      "value": "3D Lead",
      "label": "3D Lead"
    },
    {
      "value": "3D Lead/Technical Director",
      "label": "3D Lead/technical Director"
    },
    {
      "value": "3D Lighting Technical Director",
      "label": "3D Lighting Technical Director"
    },
    {
      "value": "3D Rigger",
      "label": "3D Rigger"
    },
    {
      "value": "3D Rigging Supervisor",
      "label": "3D Rigging Supervisor"
    },
    {
      "value": "3D Supervisor",
      "label": "3D Supervisor"
    },
    {
      "value": "3D Technical Artist",
      "label": "3D Technical Artist"
    },
    {
      "value": "Account Director",
      "label": "Account Director"
    },
    {
      "value": "Account Manager",
      "label": "Account Manager"
    },
    {
      "value": "Accounts Payable Coordinator",
      "label": "Accounts Payable Coordinator"
    },
    {
      "value": "AI Technical Director",
      "label": "Ai Technical Director"
    },
    {
      "value": "Animation Director",
      "label": "Animation Director"
    },
    {
      "value": "Animator (2D/After Effects)",
      "label": "Animator (2d/after Effects)"
    },
    {
      "value": "Animator (2D/Cel)",
      "label": "Animator (2d/cel)"
    },
    {
      "value": "Animator (3D)",
      "label": "Animator (3d)"
    },
    {
      "value": "Art Director",
      "label": "Art Director"
    },
    {
      "value": "Assistant Editor",
      "label": "Assistant Editor"
    },
    {
      "value": "Associate Creative Director",
      "label": "Associate Creative Director"
    },
    {
      "value": "Associate Growth Marketer",
      "label": "Associate Growth Marketer"
    },
    {
      "value": "Associate Producer",
      "label": "Associate Producer"
    },
    {
      "value": "CCO",
      "label": "Cco"
    },
    {
      "value": "CD",
      "label": "Cd"
    },
    {
      "value": "CEO",
      "label": "Ceo"
    },
    {
      "value": "Chief Creative Officer",
      "label": "Chief Creative Officer"
    },
    {
      "value": "Chief Design Officer",
      "label": "Chief Design Officer"
    },
    {
      "value": "Chief Executive Officer",
      "label": "Chief Executive Officer"
    },
    {
      "value": "Chief Financial Officer",
      "label": "Chief Financial Officer"
    },
    {
      "value": "Chief Operating Officer",
      "label": "Chief Operating Officer"
    },
    {
      "value": "Chief Talent Officer",
      "label": "Chief Talent Officer"
    },
    {
      "value": "Chief Technology Officer",
      "label": "Chief Technology Officer"
    },
    {
      "value": "Co-CEO",
      "label": "Co-ceo"
    },
    {
      "value": "Co-Founder",
      "label": "Co-founder"
    },
    {
      "value": "Colorist",
      "label": "Colorist"
    },
    {
      "value": "Communications Coordinator",
      "label": "Communications Coordinator"
    },
    {
      "value": "Communications Director",
      "label": "Communications Director"
    },
    {
      "value": "Communications Specialist",
      "label": "Communications Specialist"
    },
    {
      "value": "Compositor",
      "label": "Compositor"
    },
    {
      "value": "Concept Artist",
      "label": "Concept Artist"
    },
    {
      "value": "Concept Design Director",
      "label": "Concept Design Director"
    },
    {
      "value": "Concept Designer",
      "label": "Concept Designer"
    },
    {
      "value": "Content & Community Lead",
      "label": "Content & Community Lead"
    },
    {
      "value": "Controller",
      "label": "Controller"
    },
    {
      "value": "Copywriter",
      "label": "Copywriter"
    },
    {
      "value": "Corporate Development Manager",
      "label": "Corporate Development Manager"
    },
    {
      "value": "Creative",
      "label": "Creative"
    },
    {
      "value": "Creative Director",
      "label": "Creative Director"
    },
    {
      "value": "Creative Director/Head of Design",
      "label": "Creative Director/head Of Design"
    },
    {
      "value": "Creative Director/Head of Design and 2D",
      "label": "Creative Director/head Of Design And 2D"
    },
    {
      "value": "Creative Lead",
      "label": "Creative Lead"
    },
    {
      "value": "Creative Learning & Engagement Lead",
      "label": "Creative Learning & Engagement Lead"
    },
    {
      "value": "Creative Producer",
      "label": "Creative Producer"
    },
    {
      "value": "Creative Technologist",
      "label": "Creative Technologist"
    },
    {
      "value": "Creative Technology Lead",
      "label": "Creative Technology Lead"
    },
    {
      "value": "Design Director",
      "label": "Design Director"
    },
    {
      "value": "Design Engineer",
      "label": "Design Engineer"
    },
    {
      "value": "Designer",
      "label": "Designer"
    },
    {
      "value": "Designer/Animator",
      "label": "Designer/animator"
    },
    {
      "value": "Developer",
      "label": "Developer"
    },
    {
      "value": "Director of Automation Engineering",
      "label": "Director Of Automation Engineering"
    },
    {
      "value": "Director of Photography",
      "label": "Director Of Photography"
    },
    {
      "value": "Director of Strategy",
      "label": "Director Of Strategy"
    },
    {
      "value": "Director of Studio Operations",
      "label": "Director Of Studio Operations"
    },
    {
      "value": "Director of Systems Integration",
      "label": "Director Of Systems Integration"
    },
    {
      "value": "Director of Talent Operations",
      "label": "Director Of Talent Operations"
    },
    {
      "value": "Director, Brand Partnerships",
      "label": "Director, Brand Partnerships"
    },
    {
      "value": "Editor",
      "label": "Editor"
    },
    {
      "value": "Editorial Assistant",
      "label": "Editorial Assistant"
    },
    {
      "value": "Exec Producer",
      "label": "Exec Producer"
    },
    {
      "value": "Executive CD",
      "label": "Executive Cd"
    },
    {
      "value": "Executive Creative Director",
      "label": "Executive Creative Director"
    },
    {
      "value": "Executive Director of 2D",
      "label": "Executive Director Of 2D"
    },
    {
      "value": "Executive Director of 3D",
      "label": "Executive Director Of 3D"
    },
    {
      "value": "Executive Director of Communications",
      "label": "Executive Director Of Communications"
    },
    {
      "value": "Executive Director of Design",
      "label": "Executive Director Of Design"
    },
    {
      "value": "Executive Director of Integrated Marketing",
      "label": "Executive Director Of Integrated Marketing"
    },
    {
      "value": "Executive Producer",
      "label": "Executive Producer"
    },
    {
      "value": "Experience Operations Lead",
      "label": "Experience Operations Lead"
    },
    {
      "value": "Finance Intern",
      "label": "Finance Intern"
    },
    {
      "value": "Founder",
      "label": "Founder"
    },
    {
      "value": "FP&A Analyst",
      "label": "Fp&A Analyst"
    },
    {
      "value": "Freelance",
      "label": "Freelance"
    },
    {
      "value": "Freelance 2D Animator",
      "label": "Freelance 2D Animator"
    },
    {
      "value": "Freelance 3D Lighter",
      "label": "Freelance 3D Lighter"
    },
    {
      "value": "Freelance Designer",
      "label": "Freelance Designer"
    },
    {
      "value": "Freelancer",
      "label": "Freelancer"
    },
    {
      "value": "Frontend Developer",
      "label": "Frontend Developer"
    },
    {
      "value": "Group Creative Director",
      "label": "Group Creative Director"
    },
    {
      "value": "Group Creative Director/Head of Creative",
      "label": "Group Creative Director/head Of Creative"
    },
    {
      "value": "Group FP&A Manager",
      "label": "Group Fp&A Manager"
    },
    {
      "value": "Growth Consultant",
      "label": "Growth Consultant"
    },
    {
      "value": "Growth Marketer",
      "label": "Growth Marketer"
    },
    {
      "value": "Growth Team Operations Lead",
      "label": "Growth Team Operations Lead"
    },
    {
      "value": "Head of 2D",
      "label": "Head Of 2D"
    },
    {
      "value": "Head of 3D",
      "label": "Head Of 3D"
    },
    {
      "value": "Head of C. A.",
      "label": "Head Of C. A."
    },
    {
      "value": "Head of Copy",
      "label": "Head Of Copy"
    },
    {
      "value": "Head of Creative and Associate Creative Director",
      "label": "Head Of Creative And Associate Creative Director"
    },
    {
      "value": "Head of Creative Technology",
      "label": "Head Of Creative Technology"
    },
    {
      "value": "Head of Design",
      "label": "Head Of Design"
    },
    {
      "value": "Head of Design & Organization",
      "label": "Head Of Design & Organization"
    },
    {
      "value": "Head of Digital",
      "label": "Head Of Digital"
    },
    {
      "value": "Head of Global Systems",
      "label": "Head Of Global Systems"
    },
    {
      "value": "Head of Growth & Operations",
      "label": "Head Of Growth & Operations"
    },
    {
      "value": "Head of Operations",
      "label": "Head Of Operations"
    },
    {
      "value": "Head of Original Animation",
      "label": "Head Of Original Animation"
    },
    {
      "value": "Head of People & Culture",
      "label": "Head Of People & Culture"
    },
    {
      "value": "Head of Post",
      "label": "Head Of Post"
    },
    {
      "value": "Head of Production",
      "label": "Head Of Production"
    },
    {
      "value": "Head of Projects",
      "label": "Head Of Projects"
    },
    {
      "value": "Head of Strategy",
      "label": "Head Of Strategy"
    },
    {
      "value": "Head of Tech & Business",
      "label": "Head Of Tech & Business"
    },
    {
      "value": "Head of Technology - Infrastructure Operations",
      "label": "Head Of Technology - Infrastructure Operations"
    },
    {
      "value": "HR Coordinator",
      "label": "Hr Coordinator"
    },
    {
      "value": "HR Coordinator/ Payroll",
      "label": "Hr Coordinator/ Payroll"
    },
    {
      "value": "HR Generalist",
      "label": "Hr Generalist"
    },
    {
      "value": "HR Manager",
      "label": "Hr Manager"
    },
    {
      "value": "Illustrator",
      "label": "Illustrator"
    },
    {
      "value": "Innovation Director",
      "label": "Innovation Director"
    },
    {
      "value": "Interim Head of Operations & People",
      "label": "Interim Head Of Operations & People"
    },
    {
      "value": "IT Director",
      "label": "IT Director"
    },
    {
      "value": "IT Support Administrator",
      "label": "IT Support Administrator"
    },
    {
      "value": "IT Support Specialist",
      "label": "IT Support Specialist"
    },
    {
      "value": "Junior 2D Animator",
      "label": "Junior 2D Animator"
    },
    {
      "value": "Junior 3D Artist",
      "label": "Junior 3D Artist"
    },
    {
      "value": "Junior 3D Designer/Animator",
      "label": "Junior 3D Designer/animator"
    },
    {
      "value": "Junior Animator",
      "label": "Junior Animator"
    },
    {
      "value": "Junior Designer",
      "label": "Junior Designer"
    },
    {
      "value": "Junior Listings Coordinator",
      "label": "Junior Listings Coordinator"
    },
    {
      "value": "Junior Project Manager",
      "label": "Junior Project Manager"
    },
    {
      "value": "Junior Staff Writer and Social Media Editor",
      "label": "Junior Staff Writer And Social Media Editor"
    },
    {
      "value": "Junior Writer",
      "label": "Junior Writer"
    },
    {
      "value": "Lacy St. Productions - Studio Manager",
      "label": "Lacy St. Productions - Studio Manager"
    },
    {
      "value": "Lead 2D Animator",
      "label": "Lead 2D Animator"
    },
    {
      "value": "Lead 3D Artist",
      "label": "Lead 3D Artist"
    },
    {
      "value": "Lead 3D Designer/Animator",
      "label": "Lead 3D Designer/animator"
    },
    {
      "value": "Lead AR Artist",
      "label": "Lead Ar Artist"
    },
    {
      "value": "Lead Concept Designer",
      "label": "Lead Concept Designer"
    },
    {
      "value": "Lead Creative",
      "label": "Lead Creative"
    },
    {
      "value": "Lead Creative Technologist",
      "label": "Lead Creative Technologist"
    },
    {
      "value": "Lead Designer",
      "label": "Lead Designer"
    },
    {
      "value": "Lead IT Infrastructure Architect",
      "label": "Lead IT Infrastructure Architect"
    },
    {
      "value": "Lead Storyboard Artist",
      "label": "Lead Storyboard Artist"
    },
    {
      "value": "Lead Strategist",
      "label": "Lead Strategist"
    },
    {
      "value": "Lead Unity Developer",
      "label": "Lead Unity Developer"
    },
    {
      "value": "Line Producer",
      "label": "Line Producer"
    },
    {
      "value": "LLM Developer",
      "label": "Llm Developer"
    },
    {
      "value": "Managing Director US",
      "label": "Managing Director Us"
    },
    {
      "value": "Managing Executive Producer",
      "label": "Managing Executive Producer"
    },
    {
      "value": "Middleweight Creative",
      "label": "Middleweight Creative"
    },
    {
      "value": "Middleweight Designer",
      "label": "Middleweight Designer"
    },
    {
      "value": "Middleweight Events Producer",
      "label": "Middleweight Events Producer"
    },
    {
      "value": "Middleweight Project Manager",
      "label": "Middleweight Project Manager"
    },
    {
      "value": "Midweight Associate Editor (Partnerships)",
      "label": "Midweight Associate Editor (partnerships)"
    },
    {
      "value": "Midweight Project Manager & Account Manager",
      "label": "Midweight Project Manager & Account Manager"
    },
    {
      "value": "Modeler",
      "label": "Modeler"
    },
    {
      "value": "Motion Designer",
      "label": "Motion Designer"
    },
    {
      "value": "Motion Designer ",
      "label": "Motion Designer "
    },
    {
      "value": "New Business Lead",
      "label": "New Business Lead"
    },
    {
      "value": "Online Editor",
      "label": "Online Editor"
    },
    {
      "value": "Partnership Executive",
      "label": "Partnership Executive"
    },
    {
      "value": "Payroll Manager",
      "label": "Payroll Manager"
    },
    {
      "value": "Photo Retoucher ",
      "label": "Photo Retoucher "
    },
    {
      "value": "Pipeline, 3D Technical Director",
      "label": "Pipeline, 3D Technical Director"
    },
    {
      "value": "Post Technical Director",
      "label": "Post Technical Director"
    },
    {
      "value": "Previs Supervisor",
      "label": "Previs Supervisor"
    },
    {
      "value": "Principal 3D Artist",
      "label": "Principal 3D Artist"
    },
    {
      "value": "Principal, Digital Media",
      "label": "Principal, Digital Media"
    },
    {
      "value": "Principal, Strategy",
      "label": "Principal, Strategy"
    },
    {
      "value": "Producer",
      "label": "Producer"
    },
    {
      "value": "Product Strategy Lead",
      "label": "Product Strategy Lead"
    },
    {
      "value": "Production Assistant",
      "label": "Production Assistant"
    },
    {
      "value": "Production Coordinator",
      "label": "Production Coordinator"
    },
    {
      "value": "Production Designer",
      "label": "Production Designer"
    },
    {
      "value": "Production Director, Games",
      "label": "Production Director, Games"
    },
    {
      "value": "Production Operations Manager",
      "label": "Production Operations Manager"
    },
    {
      "value": "Production Supervisor",
      "label": "Production Supervisor"
    },
    {
      "value": "Project Manager",
      "label": "Project Manager"
    },
    {
      "value": "Resource Manager",
      "label": "Resource Manager"
    },
    {
      "value": "Rigger",
      "label": "Rigger"
    },
    {
      "value": "Sales Manager",
      "label": "Sales Manager"
    },
    {
      "value": "Senior 2D Animator",
      "label": "Senior 2D Animator"
    },
    {
      "value": "Senior 3D Animator",
      "label": "Senior 3D Animator"
    },
    {
      "value": "Senior 3D Artist",
      "label": "Senior 3D Artist"
    },
    {
      "value": "Senior 3D Designer/Animator",
      "label": "Senior 3D Designer/animator"
    },
    {
      "value": "Senior Accountant",
      "label": "Senior Accountant"
    },
    {
      "value": "Senior Accounts and New Business Manager",
      "label": "Senior Accounts And New Business Manager"
    },
    {
      "value": "Senior Animator",
      "label": "Senior Animator"
    },
    {
      "value": "Senior Art Director",
      "label": "Senior Art Director"
    },
    {
      "value": "Senior Bidding Producer",
      "label": "Senior Bidding Producer"
    },
    {
      "value": "Senior Cel Animator",
      "label": "Senior Cel Animator"
    },
    {
      "value": "Senior Concept Designer",
      "label": "Senior Concept Designer"
    },
    {
      "value": "Senior Creative",
      "label": "Senior Creative"
    },
    {
      "value": "Senior Creative Technologist",
      "label": "Senior Creative Technologist"
    },
    {
      "value": "Senior Data Analytics Engineer",
      "label": "Senior Data Analytics Engineer"
    },
    {
      "value": "Senior Designer",
      "label": "Senior Designer"
    },
    {
      "value": "Senior Designer/Animator",
      "label": "Senior Designer/animator"
    },
    {
      "value": "Senior Development Producer",
      "label": "Senior Development Producer"
    },
    {
      "value": "Senior Digital Campaign Manager",
      "label": "Senior Digital Campaign Manager"
    },
    {
      "value": "Senior Director HR",
      "label": "Senior Director Hr"
    },
    {
      "value": "Senior Director of Business and Legal Affairs",
      "label": "Senior Director Of Business And Legal Affairs"
    },
    {
      "value": "Senior Director of Production Operations",
      "label": "Senior Director Of Production Operations"
    },
    {
      "value": "Senior Director of Training and Development",
      "label": "Senior Director Of Training And Development"
    },
    {
      "value": "Senior Editor",
      "label": "Senior Editor"
    },
    {
      "value": "Senior Gameplay Engineer",
      "label": "Senior Gameplay Engineer"
    },
    {
      "value": "Senior Growth Marketer",
      "label": "Senior Growth Marketer"
    },
    {
      "value": "Senior Growth Marketer, Manager",
      "label": "Senior Growth Marketer, Manager"
    },
    {
      "value": "Senior Lead 3D Animator",
      "label": "Senior Lead 3D Animator"
    },
    {
      "value": "Senior Lead 3D Artist",
      "label": "Senior Lead 3D Artist"
    },
    {
      "value": "Senior Manager, Strategy",
      "label": "Senior Manager, Strategy"
    },
    {
      "value": "Senior Network Architect",
      "label": "Senior Network Architect"
    },
    {
      "value": "Senior Partnerships & New Business Manager",
      "label": "Senior Partnerships & New Business Manager"
    },
    {
      "value": "Senior Producer",
      "label": "Senior Producer"
    },
    {
      "value": "Senior Project and Account Manager",
      "label": "Senior Project And Account Manager"
    },
    {
      "value": "Senior Project Manager",
      "label": "Senior Project Manager"
    },
    {
      "value": "Senior Strategist",
      "label": "Senior Strategist"
    },
    {
      "value": "Senior Strategy Consultant",
      "label": "Senior Strategy Consultant"
    },
    {
      "value": "Senior Systems Architect",
      "label": "Senior Systems Architect"
    },
    {
      "value": "Senior Talent Operations Manager",
      "label": "Senior Talent Operations Manager"
    },
    {
      "value": "Social Content Creator",
      "label": "Social Content Creator"
    },
    {
      "value": "Social Media Assistant",
      "label": "Social Media Assistant"
    },
    {
      "value": "Social Media Manager",
      "label": "Social Media Manager"
    },
    {
      "value": "Sr. 2D Animator",
      "label": "Sr. 2D Animator"
    },
    {
      "value": "Sr. Business Developer",
      "label": "Sr. Business Developer"
    },
    {
      "value": "Sr. Marketing & Communications Manager",
      "label": "Sr. Marketing & Communications Manager"
    },
    {
      "value": "Sr. Technical Producer",
      "label": "Sr. Technical Producer"
    },
    {
      "value": "Staff Accountant",
      "label": "Staff Accountant"
    },
    {
      "value": "Staff Writer",
      "label": "Staff Writer"
    },
    {
      "value": "Storyboard Artist",
      "label": "Storyboard Artist"
    },
    {
      "value": "Strategist",
      "label": "Strategist"
    },
    {
      "value": "Strategy Director",
      "label": "Strategy Director"
    },
    {
      "value": "Studio Assistant",
      "label": "Studio Assistant"
    },
    {
      "value": "Studio Coordinator",
      "label": "Studio Coordinator"
    },
    {
      "value": "Studio Manager",
      "label": "Studio Manager"
    },
    {
      "value": "Systems Admin",
      "label": "Systems Admin"
    },
    {
      "value": "Talent Coordinator",
      "label": "Talent Coordinator"
    },
    {
      "value": "Talent Operations Associate",
      "label": "Talent Operations Associate"
    },
    {
      "value": "Talent Operations Coordinator",
      "label": "Talent Operations Coordinator"
    },
    {
      "value": "Talent Operations Manager",
      "label": "Talent Operations Manager"
    },
    {
      "value": "Tech Director",
      "label": "Tech Director"
    },
    {
      "value": "Technical Program Manager",
      "label": "Technical Program Manager"
    },
    {
      "value": "Unassigned",
      "label": "Unassigned"
    },
    {
      "value": "UX Designer",
      "label": "UX Designer"
    },
    {
      "value": "UX Director",
      "label": "UX Director"
    },
    {
      "value": "Visual Designer",
      "label": "Visual Designer"
    }
  ],
  "statuses": [
    {
      "value": "",
      "label": "All Status"
    },
    {
      "value": "ACTIVE",
      "label": "Active"
    },
    {
      "value": "PASSWORD_EXPIRED",
      "label": "Password Expired"
    },
    {
      "value": "PROVISIONED",
      "label": "Provisioned"
    },
    {
      "value": "RECOVERY",
      "label": "Recovery"
    },
    {
      "value": "STAGED",
      "label": "Staged"
    },
    {
      "value": "SUSPENDED",
      "label": "Suspended"
    }
  ],
  "securityClearances": [
    {
      "value": "",
      "label": "All Clearance Levels"
    }
  ]
};
